modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/Khajiitos/PotionVapes/issues"

[[mods]]
modId = "potionvapes"
version = "${version}"
logoFile="icon.png"
displayName = "Potion Vapes"
authors = "Khajiitos"
displayURL="https://github.com/Khajiitos/PotionVapes"
description = '''Adds useful vapes to the game!'''
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.potionvapes]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.potionvapes]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
